site_name: AsmetaL Syntax - Quick Guide
site_description: AsmetaL (AsmM) concrete syntax quick guide
theme:
  name: material
nav:
  - Home: index.md
  - Structure of an ASM: 01-structure-of-an-asm.md
  - Domain declarations: 02_domain_declaration.md
  - Function declarations: 03_function_declarations.md
  - Terms: 04_terms.md
  - Rules: 05_transition_rules.md
  

use_directory_urls: true
